### ISSUE TITLE
Secure Quick Setting Tiles on Lockscreen

### ISSUE THREAD

**Issue by bobbyamarthaa** [PixelOS-Pixelish/packages_apps_Settings#24]
I check on PixelOS blog on lastest post (April 2024),  Secure quick setting tiles on lockscreen is on Feature list. 
but i try to search on Setting, its seems not available. 
I've checked almost everywhere.
Tried searching in the search bar also didn't show anything about it.
checking on Security & Privacy didn't find it either.

**Comment by Twel12** [comment]
This is something that won't appear in the settings application. It just means that QS tiles are secured on lockscreen basically you cannot use them without unlocking your device like for example bluetooth, mobile data or important tiles that may have effect on the device with unauthorised access. And for such issues please use the telegram support chat rather than opening an issue :)

**Comment by bobbyamarthaa** [comment]
this problem still appears on lastest PixelOS
